export const RESTORE_FAILURE_CODES = [
  "TARGET_NOT_AUTHORIZED",
  "BACKUP_VERIFICATION_FAILED",
  "BACKUP_SCHEMA_INCOMPATIBLE",
  "INSERTION_FAILED",
  "COUNT_MISMATCH",
  "FOREIGN_KEY_VIOLATION",
  "DOMAIN_INVARIANT_FAILED",
  "TENANT_AUDIT_FAILED",
  "APPLICATION_READ_FAILED",
  "FILE_RECOVERY_FAILED",
  "APP_SMOKE_FAILED",
  "FIXTURE_CREATION_FAILED",
  "FIXTURE_CLEANUP_FAILED",
  "WORKITEM_AUDIT_FAILED",
  "PRISMA_DRIFT_FAILED",
  "UNKNOWN",
] as const;

export type RestoreFailureCode = (typeof RESTORE_FAILURE_CODES)[number];
