/**
 * Explicit application-table privilege inventory for the restricted PostgreSQL
 * runtime role. Environment-local and Prisma migration tables are excluded.
 */
export const RUNTIME_DATABASE_TABLES = [
  "Organization",
  "OrganizationMembership",
  "User",
  "Client",
  "Insurer",
  "Policy",
  "Receipt",
  "PolicyEndorsement",
  "Payment",
  "Commission",
  "Task",
  "WorkItem",
  "Claim",
  "Quote",
  "Document",
  "SystemSetting",
  "ActivityLog",
  "AssistantActionDraft",
  "NotificationChannel",
  "NotificationPreference",
  "NotificationEvent",
  "PolicyInsuredParty",
  "PolicyInsuredAsset",
  "TelegramLinkToken",
  "LedgerImportBatch",
  "LedgerImportRow",
  "LedgerImportAction",
  "LedgerImportIssue",
  "TelegramDraft",
  "MaintenanceRun",
  "ReceiptReconciliationIssue",
  "PolicyRenewalSuggestion",
  "DataQualitySuppressionRule",
  "AssistantReport",
  "AssistantReportSignal",
  "AssistantAiRun",
  "AssistantAiAttempt",
  "Alert",
  "SecurityEventAggregate",
  "TelegramWebhookUpdate",
] as const;

export const RUNTIME_DATABASE_ROLE = "policydesk_runtime";
