import "server-only";

import { createHash } from "node:crypto";
import type { Prisma } from "@/generated/prisma/client";

export const DEMO_SEED_VERSION = "demo-2026-08-v1";

const addDays = (date: Date, days: number) => new Date(date.getTime() + days * 86_400_000);
const id = (organizationId: string, type: string, ordinal: number) => `${organizationId}:demo:${type}:${String(ordinal).padStart(3, "0")}`;
const hash = (value: string) => createHash("sha256").update(value).digest("hex");

/** Deterministic, synthetic portfolio used by every reset/provisioning run. */
export async function seedDemoBaseline(tx: Prisma.TransactionClient, organizationId: string, actorUserId: string) {
  const now = new Date();
  const insurerA = id(organizationId, "insurer", 1);
  const insurerB = id(organizationId, "insurer", 2);
  await tx.insurer.upsert({ where: { id: insurerA }, update: { organizationId, name: "DEMO Aseguradora Horizonte", status: "ACTIVE" }, create: { id: insurerA, organizationId, name: "DEMO Aseguradora Horizonte", status: "ACTIVE" } });
  await tx.insurer.upsert({ where: { id: insurerB }, update: { organizationId, name: "DEMO Seguros del Centro", status: "ACTIVE" }, create: { id: insurerB, organizationId, name: "DEMO Seguros del Centro", status: "ACTIVE" } });

  const clients = [
    { id: id(organizationId, "client", 1), name: "DEMO Ana López", type: "PERSON", email: "ana.lopez@example.invalid", phone: "" },
    { id: id(organizationId, "client", 2), name: "DEMO Grupo Roble S.A. de C.V.", type: "COMPANY", email: "grupo.roble@example.invalid", phone: "" },
    { id: id(organizationId, "client", 3), name: "DEMO Carlos Méndez", type: "PERSON", email: "carlos.mendez@example.invalid", phone: "" },
  ];
  for (const client of clients) {
    await tx.client.upsert({
      where: { id: client.id },
      update: { organizationId, fullName: client.name, type: client.type, email: client.email, phone: client.phone, status: "ACTIVE", portfolioOwnerId: actorUserId, createdById: actorUserId, updatedById: actorUserId },
      create: { id: client.id, organizationId, fullName: client.name, type: client.type, email: client.email, phone: client.phone, status: "ACTIVE", portfolioOwnerId: actorUserId, createdById: actorUserId, updatedById: actorUserId },
    });
  }

  const policies = [
    { ordinal: 1, clientId: clients[0].id, insurerId: insurerA, number: "DEMO-AUTO-001", type: "AUTO", start: -180, end: 15, premium: 18500 },
    { ordinal: 2, clientId: clients[1].id, insurerId: insurerB, number: "DEMO-GMM-002", type: "GMM", start: -90, end: 180, premium: 74000 },
    { ordinal: 3, clientId: clients[2].id, insurerId: insurerA, number: "DEMO-HOGAR-003", type: "HOME", start: -365, end: -10, premium: 9200 },
    { ordinal: 4, clientId: clients[1].id, insurerId: insurerA, number: "DEMO-EMPRESA-004", type: "BUSINESS", start: -30, end: 335, premium: 125000 },
  ];
  const policyIds: string[] = [];
  for (const policyInput of policies) {
    const policyId = id(organizationId, "policy", policyInput.ordinal);
    policyIds.push(policyId);
    await tx.policy.upsert({
      where: { id: policyId },
      update: { organizationId, clientId: policyInput.clientId, insurerId: policyInput.insurerId, policyNumber: policyInput.number, policyType: policyInput.type, status: policyInput.end < 0 ? "EXPIRED" : "ACTIVE", startDate: addDays(now, policyInput.start), endDate: addDays(now, policyInput.end), premiumAmount: policyInput.premium, currency: "MXN", paymentFrequency: "ANNUAL", createdById: actorUserId, updatedById: actorUserId },
      create: { id: policyId, organizationId, clientId: policyInput.clientId, insurerId: policyInput.insurerId, policyNumber: policyInput.number, policyType: policyInput.type, status: policyInput.end < 0 ? "EXPIRED" : "ACTIVE", startDate: addDays(now, policyInput.start), endDate: addDays(now, policyInput.end), premiumAmount: policyInput.premium, currency: "MXN", paymentFrequency: "ANNUAL", createdById: actorUserId, updatedById: actorUserId },
    });
    const receiptId = id(organizationId, "receipt", policyInput.ordinal);
    await tx.receipt.upsert({
      where: { id: receiptId },
      update: { organizationId, policyId, clientId: policyInput.clientId, insurerId: policyInput.insurerId, receiptNumber: `DEMO-REC-${String(policyInput.ordinal).padStart(3, "0")}`, periodStartDate: addDays(now, policyInput.start), periodEndDate: addDays(now, policyInput.end), dueDate: addDays(now, policyInput.end - 30), amount: policyInput.premium, currency: "MXN", status: policyInput.ordinal === 3 ? "OVERDUE" : policyInput.ordinal === 1 ? "PAID" : "PENDING", paidDate: policyInput.ordinal === 1 ? addDays(now, -5) : null, paymentMethod: policyInput.ordinal === 1 ? "TRANSFER" : null, createdById: actorUserId, updatedById: actorUserId },
      create: { id: receiptId, organizationId, policyId, clientId: policyInput.clientId, insurerId: policyInput.insurerId, receiptNumber: `DEMO-REC-${String(policyInput.ordinal).padStart(3, "0")}`, periodStartDate: addDays(now, policyInput.start), periodEndDate: addDays(now, policyInput.end), dueDate: addDays(now, policyInput.end - 30), amount: policyInput.premium, currency: "MXN", status: policyInput.ordinal === 3 ? "OVERDUE" : policyInput.ordinal === 1 ? "PAID" : "PENDING", paidDate: policyInput.ordinal === 1 ? addDays(now, -5) : null, paymentMethod: policyInput.ordinal === 1 ? "TRANSFER" : null, createdById: actorUserId, updatedById: actorUserId },
    });
    if (policyInput.ordinal === 1) {
      await tx.payment.upsert({ where: { id: id(organizationId, "payment", 1) }, update: { organizationId, receiptId, policyId, clientId: policyInput.clientId, amount: policyInput.premium, currency: "MXN", status: "POSTED", paidDate: addDays(now, -5), paymentMethod: "TRANSFER", createdById: actorUserId, updatedById: actorUserId }, create: { id: id(organizationId, "payment", 1), organizationId, receiptId, policyId, clientId: policyInput.clientId, amount: policyInput.premium, currency: "MXN", status: "POSTED", paidDate: addDays(now, -5), paymentMethod: "TRANSFER", createdById: actorUserId, updatedById: actorUserId } });
      await tx.commission.upsert({ where: { id: id(organizationId, "commission", 1) }, update: { organizationId, policyId, receiptId, clientId: policyInput.clientId, insurerId: policyInput.insurerId, expectedAmount: policyInput.premium * 0.1, percentage: 10, expectedDate: addDays(now, 25), status: "PENDING" }, create: { id: id(organizationId, "commission", 1), organizationId, policyId, receiptId, clientId: policyInput.clientId, insurerId: policyInput.insurerId, expectedAmount: policyInput.premium * 0.1, percentage: 10, expectedDate: addDays(now, 25), status: "PENDING" } });
    }
    if (policyInput.ordinal === 2) {
      await tx.payment.upsert({ where: { id: id(organizationId, "payment", 2) }, update: { organizationId, receiptId, policyId, clientId: policyInput.clientId, amount: policyInput.premium, currency: "MXN", status: "REVERSED", paidDate: addDays(now, -12), paymentMethod: "TRANSFER", reversedById: actorUserId, reversedAt: addDays(now, -10), reversalReason: "DEMO reversal example", createdById: actorUserId, updatedById: actorUserId }, create: { id: id(organizationId, "payment", 2), organizationId, receiptId, policyId, clientId: policyInput.clientId, amount: policyInput.premium, currency: "MXN", status: "REVERSED", paidDate: addDays(now, -12), paymentMethod: "TRANSFER", reversedById: actorUserId, reversedAt: addDays(now, -10), reversalReason: "DEMO reversal example", createdById: actorUserId, updatedById: actorUserId } });
    }
  }

  const endorsementId = id(organizationId, "endorsement", 1);
  await tx.policyEndorsement.upsert({
    where: { id: endorsementId },
    update: { organizationId, endorsementNumber: "DEMO-END-001", policyId: policyIds[1], status: "ACTIVE", startDate: addDays(now, -15), endDate: addDays(now, 180), amount: 3500, currency: "MXN", concept: "Ajuste sintético de cobertura", createdById: actorUserId, updatedById: actorUserId },
    create: { id: endorsementId, organizationId, endorsementNumber: "DEMO-END-001", policyId: policyIds[1], status: "ACTIVE", startDate: addDays(now, -15), endDate: addDays(now, 180), amount: 3500, currency: "MXN", concept: "Ajuste sintético de cobertura", createdById: actorUserId, updatedById: actorUserId },
  });
  await tx.receipt.update({ where: { id: id(organizationId, "receipt", 2) }, data: { endorsementId } });

  const maintenanceRunId = id(organizationId, "maintenance-run", 1);
  await tx.maintenanceRun.upsert({ where: { id: maintenanceRunId }, update: { organizationId, type: "DEMO_DATA_QUALITY", status: "COMPLETED", summaryJson: JSON.stringify({ synthetic: true }), completedAt: now, createdById: actorUserId }, create: { id: maintenanceRunId, organizationId, type: "DEMO_DATA_QUALITY", status: "COMPLETED", summaryJson: JSON.stringify({ synthetic: true }), startedAt: addDays(now, -1), completedAt: now, createdById: actorUserId } });
  const suppressionRuleId = id(organizationId, "suppression-rule", 1);
  await tx.dataQualitySuppressionRule.upsert({ where: { id: suppressionRuleId }, update: { organizationId, category: "DEMO", issueCode: "SYNTHETIC_EXAMPLE", criteriaJson: JSON.stringify({ source: "demo-seed" }), active: true, reason: "Synthetic demonstration record", createdById: actorUserId, reviewedById: actorUserId, reviewedAt: now }, create: { id: suppressionRuleId, organizationId, category: "DEMO", issueCode: "SYNTHETIC_EXAMPLE", criteriaJson: JSON.stringify({ source: "demo-seed" }), active: true, reason: "Synthetic demonstration record", createdById: actorUserId, reviewedById: actorUserId, reviewedAt: now } });
  const reconciliationIssueId = id(organizationId, "reconciliation-issue", 1);
  await tx.receiptReconciliationIssue.upsert({ where: { id: reconciliationIssueId }, update: { organizationId, maintenanceRunId, receiptId: id(organizationId, "receipt", 2), policyId: policyIds[1], reason: "DEMO reversed payment requires review", status: "OPEN", detailsJson: JSON.stringify({ synthetic: true }), expectedAmount: policies[1].premium, paidAmount: 0, suppressedByRuleId: suppressionRuleId }, create: { id: reconciliationIssueId, organizationId, maintenanceRunId, receiptId: id(organizationId, "receipt", 2), policyId: policyIds[1], reason: "DEMO reversed payment requires review", status: "OPEN", detailsJson: JSON.stringify({ synthetic: true }), expectedAmount: policies[1].premium, paidAmount: 0, suppressedByRuleId: suppressionRuleId } });
  const renewalSuggestionId = id(organizationId, "renewal-suggestion", 1);
  await tx.policyRenewalSuggestion.upsert({ where: { id: renewalSuggestionId }, update: { organizationId, maintenanceRunId, sourcePolicyId: policyIds[0], targetPolicyId: policyIds[3], status: "PENDING", confidence: 0.91, reason: "DEMO renewal candidate", suppressedByRuleId: null }, create: { id: renewalSuggestionId, organizationId, maintenanceRunId, sourcePolicyId: policyIds[0], targetPolicyId: policyIds[3], status: "PENDING", confidence: 0.91, reason: "DEMO renewal candidate" } });

  const documentId = id(organizationId, "document", 1);
  await tx.document.upsert({ where: { id: documentId }, update: { organizationId, clientId: clients[0].id, policyId: policyIds[0], documentType: "POLICY", fileName: "DEMO-policy-metadata.pdf", filePath: `demo://${organizationId}/synthetic/policy-001`, mimeType: "application/pdf", notes: "Metadata-only synthetic example; no outbound file exists.", createdById: actorUserId, updatedById: actorUserId }, create: { id: documentId, organizationId, clientId: clients[0].id, policyId: policyIds[0], documentType: "POLICY", fileName: "DEMO-policy-metadata.pdf", filePath: `demo://${organizationId}/synthetic/policy-001`, mimeType: "application/pdf", notes: "Metadata-only synthetic example; no outbound file exists.", createdById: actorUserId, updatedById: actorUserId } });
  await tx.activityLog.upsert({ where: { id: id(organizationId, "activity", 1) }, update: { organizationId, entityType: "Policy", entityId: policyIds[0], action: "DEMO_SEED_CREATED", newValue: JSON.stringify({ synthetic: true, seedVersion: DEMO_SEED_VERSION }), userId: actorUserId }, create: { id: id(organizationId, "activity", 1), organizationId, entityType: "Policy", entityId: policyIds[0], action: "DEMO_SEED_CREATED", newValue: JSON.stringify({ synthetic: true, seedVersion: DEMO_SEED_VERSION }), userId: actorUserId } });
  const notificationPreferenceId = id(organizationId, "notification-preference", 1);
  await tx.notificationPreference.upsert({ where: { userId_eventType_channelType: { userId: actorUserId, eventType: "RENEWAL", channelType: "IN_APP" } }, update: { id: notificationPreferenceId, organizationId, enabled: true, minPriority: "MEDIUM" }, create: { id: notificationPreferenceId, organizationId, userId: actorUserId, eventType: "RENEWAL", channelType: "IN_APP", enabled: true, minPriority: "MEDIUM" } });
  await tx.notificationEvent.upsert({ where: { id: id(organizationId, "notification", 1) }, update: { organizationId, type: "RENEWAL", title: "DEMO renovación próxima", body: "Ejemplo sintético de notificación.", priority: "HIGH", userId: actorUserId, clientId: clients[0].id, policyId: policyIds[0], dedupeKey: `demo-renewal:${organizationId}`, channelType: "IN_APP", status: "PENDING" }, create: { id: id(organizationId, "notification", 1), organizationId, type: "RENEWAL", title: "DEMO renovación próxima", body: "Ejemplo sintético de notificación.", priority: "HIGH", userId: actorUserId, clientId: clients[0].id, policyId: policyIds[0], dedupeKey: `demo-renewal:${organizationId}`, channelType: "IN_APP", status: "PENDING" } });

  const claimId = id(organizationId, "claim", 1);
  await tx.claim.upsert({ where: { id: claimId }, update: { organizationId, folio: "DEMO-CLAIM-001", clientId: clients[0].id, policyId: policyIds[0], insurerId: insurerA, claimType: "COLISION", description: "Ejemplo sintético para probar el flujo de siniestros.", incidentDate: addDays(now, -20), reportedDate: addDays(now, -18), amountClaimed: 42000, status: "IN_PROGRESS", createdById: actorUserId, updatedById: actorUserId }, create: { id: claimId, organizationId, folio: "DEMO-CLAIM-001", clientId: clients[0].id, policyId: policyIds[0], insurerId: insurerA, claimType: "COLISION", description: "Ejemplo sintético para probar el flujo de siniestros.", incidentDate: addDays(now, -20), reportedDate: addDays(now, -18), amountClaimed: 42000, status: "IN_PROGRESS", createdById: actorUserId, updatedById: actorUserId } });
  await tx.claimChecklistItem.upsert({ where: { claimId_requirementCode: { claimId, requirementCode: "INE" } }, update: { organizationId, label: "Identificación oficial", status: "REQUESTED" }, create: { id: id(organizationId, "checklist", 1), organizationId, claimId, requirementCode: "INE", label: "Identificación oficial", status: "REQUESTED" } });

  await tx.task.upsert({ where: { id: id(organizationId, "task", 1) }, update: { organizationId, folio: "DEMO-TASK-001", clientId: clients[0].id, policyId: policyIds[0], insurerId: insurerA, title: "Dar seguimiento a renovación DEMO", description: "Ejemplo sintético de tarea", taskType: "RENEWAL", status: "OPEN", priority: "HIGH", dueDate: addDays(now, 7), createdById: actorUserId, updatedById: actorUserId }, create: { id: id(organizationId, "task", 1), organizationId, folio: "DEMO-TASK-001", clientId: clients[0].id, policyId: policyIds[0], insurerId: insurerA, title: "Dar seguimiento a renovación DEMO", description: "Ejemplo sintético de tarea", taskType: "RENEWAL", status: "OPEN", priority: "HIGH", dueDate: addDays(now, 7), createdById: actorUserId, updatedById: actorUserId } });
  await tx.workItem.upsert({ where: { organizationId_sourceType_sourceId: { organizationId, sourceType: "DEMO", sourceId: "demo-work-item-1" } }, update: { organizationId, sourceType: "DEMO", sourceId: "demo-work-item-1", workItemType: "TASK", taskType: "RENEWAL", status: "OPEN", priority: "HIGH", folio: "DEMO-WORK-001", title: "DEMO renewal follow-up", description: "Synthetic work item", entityType: "Policy", entityId: policyIds[0], clientId: clients[0].id, policyId: policyIds[0], insurerId: insurerA, dueDate: addDays(now, 7), assignedToId: actorUserId }, create: { id: id(organizationId, "work", 1), organizationId, sourceType: "DEMO", sourceId: "demo-work-item-1", workItemType: "TASK", taskType: "RENEWAL", status: "OPEN", priority: "HIGH", folio: "DEMO-WORK-001", title: "DEMO renewal follow-up", description: "Synthetic work item", entityType: "Policy", entityId: policyIds[0], clientId: clients[0].id, policyId: policyIds[0], insurerId: insurerA, dueDate: addDays(now, 7), assignedToId: actorUserId } });
  await tx.alert.upsert({ where: { id: id(organizationId, "alert", 1) }, update: { organizationId, alertType: "RENEWAL", severity: "HIGH", title: "Póliza DEMO próxima a vencer", description: "Alerta sintética", entityType: "Policy", entityId: policyIds[0], clientId: clients[0].id, policyId: policyIds[0], status: "OPEN" }, create: { id: id(organizationId, "alert", 1), organizationId, alertType: "RENEWAL", severity: "HIGH", title: "Póliza DEMO próxima a vencer", description: "Alerta sintética", entityType: "Policy", entityId: policyIds[0], clientId: clients[0].id, policyId: policyIds[0], status: "OPEN" } });

  const sourceId = id(organizationId, "knowledge-source", 1);
  const knowledgeContentHash = hash(`${organizationId}:${DEMO_SEED_VERSION}:knowledge-content`);
  const knowledgeManifestHash = hash(`${knowledgeContentHash}:manifest`);
  await tx.knowledgeSource.upsert({ where: { id: sourceId }, update: { organizationId, title: "DEMO Guía de atención", version: DEMO_SEED_VERSION, status: "ACTIVE", contentHash: knowledgeContentHash, manifestHash: knowledgeManifestHash, integrityVersion: "CHUNK_MANIFEST_V1", integrityVerifiedAt: now, createdById: actorUserId }, create: { id: sourceId, organizationId, title: "DEMO Guía de atención", version: DEMO_SEED_VERSION, status: "ACTIVE", contentHash: knowledgeContentHash, manifestHash: knowledgeManifestHash, integrityVersion: "CHUNK_MANIFEST_V1", integrityVerifiedAt: now, createdById: actorUserId } });
  await tx.knowledgeChunk.upsert({ where: { sourceId_ordinal: { sourceId, ordinal: 0 } }, update: { organizationId, content: "Contenido sintético para probar búsqueda y Nora.", section: "Demo" }, create: { id: id(organizationId, "knowledge-chunk", 1), organizationId, sourceId, ordinal: 0, content: "Contenido sintético para probar búsqueda y Nora.", section: "Demo" } });

  const reportId = id(organizationId, "assistant-report", 1);
  await tx.assistantReport.upsert({ where: { id: reportId }, update: { organizationId, kind: "DEMO", themeKey: "renewal", themeLabel: "Renovaciones", status: "COLLECTING", title: "DEMO resumen de renovaciones", summary: "Ejemplo sintético para explorar Nora.", recommendation: "Revisar las pólizas próximas a vencer.", plan: "Confirmar datos antes de contactar a un destinatario.", evidenceJson: JSON.stringify({ policyId: policyIds[0] }), detailsJson: JSON.stringify({ synthetic: true }), signalCount: 1, severity: "MEDIUM", firstSignalAt: now, lastSignalAt: now }, create: { id: reportId, organizationId, kind: "DEMO", themeKey: "renewal", themeLabel: "Renovaciones", status: "COLLECTING", title: "DEMO resumen de renovaciones", summary: "Ejemplo sintético para explorar Nora.", recommendation: "Revisar las pólizas próximas a vencer.", plan: "Confirmar datos antes de contactar a un destinatario.", evidenceJson: JSON.stringify({ policyId: policyIds[0] }), detailsJson: JSON.stringify({ synthetic: true }), signalCount: 1, severity: "MEDIUM", firstSignalAt: now, lastSignalAt: now } });
  await tx.assistantReportSignal.upsert({ where: { id: id(organizationId, "assistant-signal", 1) }, update: { organizationId, reportId, signalKind: "RENEWAL", source: "DEMO_SEED", title: "Póliza próxima a vencer", inputJson: JSON.stringify({ policyId: policyIds[0] }), outputJson: JSON.stringify({ synthetic: true }) }, create: { id: id(organizationId, "assistant-signal", 1), organizationId, reportId, signalKind: "RENEWAL", source: "DEMO_SEED", title: "Póliza próxima a vencer", inputJson: JSON.stringify({ policyId: policyIds[0] }), outputJson: JSON.stringify({ synthetic: true }) } });
  const aiRunId = id(organizationId, "assistant-ai-run", 1);
  await tx.assistantAiRun.upsert({ where: { id: aiRunId }, update: { organizationId, userId: actorUserId, userRole: "ADMIN", operation: "DEMO_EXAMPLE", tier: "LOCAL", requestedModel: "demo", finalModel: "demo", status: "SUCCEEDED", attemptCount: 1, fallbackCount: 0, reportId, estimatedCostUsd: 0 }, create: { id: aiRunId, organizationId, userId: actorUserId, userRole: "ADMIN", operation: "DEMO_EXAMPLE", tier: "LOCAL", requestedModel: "demo", finalModel: "demo", status: "SUCCEEDED", attemptCount: 1, fallbackCount: 0, reportId, estimatedCostUsd: 0 } });
  await tx.assistantAiAttempt.upsert({ where: { id: id(organizationId, "assistant-ai-attempt", 1) }, update: { organizationId, runId: aiRunId, attemptNumber: 1, tier: "LOCAL", requestedModel: "demo", finalModel: "demo", status: "SUCCEEDED", provider: "DEMO_SEED" }, create: { id: id(organizationId, "assistant-ai-attempt", 1), organizationId, runId: aiRunId, attemptNumber: 1, tier: "LOCAL", requestedModel: "demo", finalModel: "demo", status: "SUCCEEDED", provider: "DEMO_SEED" } });
  await tx.assistantActionDraft.upsert({ where: { id: id(organizationId, "assistant-draft", 1) }, update: { organizationId, userId: actorUserId, title: "DEMO acción pendiente", summary: "Ejemplo sintético que requiere confirmación.", reply: "No se enviará nada hasta confirmar y reemplazar los datos de contacto.", entityType: "Policy", operation: "REVIEW", targetLabel: "DEMO-AUTO-001", payloadJson: JSON.stringify({ synthetic: true }), status: "PENDING", expiresAt: addDays(now, 7) }, create: { id: id(organizationId, "assistant-draft", 1), organizationId, userId: actorUserId, title: "DEMO acción pendiente", summary: "Ejemplo sintético que requiere confirmación.", reply: "No se enviará nada hasta confirmar y reemplazar los datos de contacto.", entityType: "Policy", operation: "REVIEW", targetLabel: "DEMO-AUTO-001", payloadJson: JSON.stringify({ synthetic: true }), status: "PENDING", expiresAt: addDays(now, 7) } });
}
